# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "nvme" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b7f67983-6ee9-4c68-9bc1-800923fc801e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b7f67983-6ee9-4c68-9bc1-800923fc801e".device = "/dev/disk/by-uuid/b7f67983-6ee9-4c68-9bc1-800923fc801e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9DB7-5E39";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Deliberate swap design: zram only (see features.swap in variables.nix).
  # The previous LUKS swap mapper had no boot.initrd.luks.devices entry, so it
  # could never unlock; do not reintroduce it without a matching unlock path.
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # Explicit AMD firmware/microcode intent (do not leave this chained to an unset default).
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = true;
}
