# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "nvme" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b7f67983-6ee9-4c68-9bc1-800923fc801e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b7f67983-6ee9-4c68-9bc1-800923fc801e".device = "/dev/disk/by-uuid/b7f67983-6ee9-4c68-9bc1-800923fc801e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9DB7-5E39";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ac3396b5-2913-41e7-9dde-67fd9ca8762f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
